//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace To_Do_List_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class TasksDB
    {
        public string TaskName { get; set; }
        public string Description { get; set; }
        public System.DateTime DueDate { get; set; }
        public string Category { get; set; }
    }
}
